import pandas as pd
import random
from faker import Faker


# --------------------------------------------------
# SETUP
# --------------------------------------------------

fake = Faker()


PAYMENT_MODES = [
    "UPI",
    "Credit Card",
    "Debit Card",
    "Cash",
    "Net Banking"
]


ORDER_STATUSES = [
    "Completed",
    "Processing",
    "Shipped",
    "Cancelled"
]


RETURN_REASONS = [
    "Damaged",
    "Wrong Product",
    "Defective",
    "Changed Mind",
    "Not as Described"
]


REFUND_STATUSES = [
    "Pending",
    "Processed",
    "Rejected"
]


# --------------------------------------------------
# LOAD PRODUCTS
# --------------------------------------------------

def load_products():

    products_df = pd.read_csv(
        "datasets/products.csv"
    )

    # product_id is generated by MySQL
    # using AUTO_INCREMENT.
    # Recreate it for Python.

    products_df["product_id"] = range(
        1,
        len(products_df) + 1
    )

    products_df = products_df[
        [
            "product_id",
            "unit_price"
        ]
    ]

    return products_df


# --------------------------------------------------
# GENERATE ORDER
# --------------------------------------------------

def generate_order(
    customers,
    employees,
    regions
):

    customer = customers.sample(
        n=1
    ).iloc[0]

    employee = employees.sample(
        n=1
    ).iloc[0]

    region = regions.sample(
        n=1
    ).iloc[0]

    order = {

        "customer_id":
            customer["customer_id"],

        "employee_id":
            employee["employee_id"],

        "region_id":
            region["region_id"],

        "order_date":
            fake.date_between(
                start_date="-2y",
                end_date="today"
            ),

        "payment_mode":
            random.choice(
                PAYMENT_MODES
            ),

        "order_status":
            random.choice(
                ORDER_STATUSES
            )
    }

    return order


# --------------------------------------------------
# GENERATE ORDER ITEMS
# --------------------------------------------------

def generate_order_items(
    order_id,
    products
):

    # Each order contains
    # between 1 and 5 products.

    item_count = random.randint(
        1,
        5
    )

    selected_products = products.sample(
        n=item_count
    )

    order_items = []

    for _, product in selected_products.iterrows():

        quantity = random.randint(
            1,
            10
        )

        discount = round(
            random.uniform(
                0,
                20
            ),
            2
        )

        order_item = {

            "order_id":
                order_id,

            "product_id":
                product["product_id"],

            "quantity":
                quantity,

            "unit_price":
                product["unit_price"],

            "discount":
                discount
        }

        order_items.append(
            order_item
        )

    return order_items


# --------------------------------------------------
# CALCULATE ORDER TOTAL
# --------------------------------------------------

def calculate_order_total(
    order_items
):

    total_amount = 0

    for item in order_items:

        gross_amount = (
            item["quantity"]
            * item["unit_price"]
        )

        discount_amount = (
            gross_amount
            * (
                item["discount"]
                / 100
            )
        )

        final_amount = (
            gross_amount
            - discount_amount
        )

        total_amount += final_amount

    return round(
        total_amount,
        2
    )


# --------------------------------------------------
# GENERATE PAYMENT
# --------------------------------------------------

def generate_payment(
    order
):

    if order["order_status"] == "Completed":

        payment_status = random.choice(
            [
                "Paid",
                "Paid",
                "Paid",
                "Refunded"
            ]
        )

    elif order["order_status"] == "Shipped":

        payment_status = random.choice(
            [
                "Paid",
                "Paid",
                "Pending"
            ]
        )

    elif order["order_status"] == "Processing":

        payment_status = random.choice(
            [
                "Paid",
                "Pending"
            ]
        )

    else:

        # Cancelled order

        payment_status = random.choice(
            [
                "Failed",
                "Refunded"
            ]
        )

    payment = {

        "order_id":
            order["order_id"],

        "payment_mode":
            order["payment_mode"],

        "payment_status":
            payment_status,

        "payment_date":
            order["order_date"],

        "amount":
            order["total_amount"]
    }

    return payment


# --------------------------------------------------
# GENERATE RETURNS
# --------------------------------------------------

def generate_return(
    order,
    order_items
):

    returns = []

    for item in order_items:

        # Approximately 10% of
        # order items are returned.

        if random.random() < 0.10:

            return_record = {

                "order_item_id":
                    item["order_item_id"],

                "return_date":
                    fake.date_between(
                        start_date=
                            order["order_date"],

                        end_date=
                            "today"
                    ),

                "return_reason":
                    random.choice(
                        RETURN_REASONS
                    ),

                "refund_status":
                    random.choice(
                        REFUND_STATUSES
                    )
            }

            returns.append(
                return_record
            )

    return returns

def save_to_csv(
    orders_df,
    order_items_df,
    payments_df,
    returns_df
):

    orders_df.to_csv(
        "datasets/generated_orders.csv",
        index=False
    )

    order_items_df.to_csv(
        "datasets/generated_order_items.csv",
        index=False
    )

    payments_df.to_csv(
        "datasets/generated_payments.csv",
        index=False
    )

    returns_df.to_csv(
        "datasets/generated_returns.csv",
        index=False
    )

    print("\nCSV files saved successfully!")

# --------------------------------------------------
# MAIN
# --------------------------------------------------

def main():

    # ----------------------------------------------
    # LOAD DATASETS
    # ----------------------------------------------

    customers = pd.read_csv(
        "datasets/customers.csv"
    )

    employees = pd.read_csv(
        "datasets/employees.csv"
    )

    regions = pd.read_csv(
        "datasets/regions.csv"
    )

    products = load_products()


    # ----------------------------------------------
    # RECREATE AUTO_INCREMENT IDs
    # ----------------------------------------------

    customers["customer_id"] = range(
        1,
        len(customers) + 1
    )

    employees["employee_id"] = range(
        1,
        len(employees) + 1
    )


    # ----------------------------------------------
    # STORAGE
    # ----------------------------------------------

    orders = []

    order_items = []

    payments = []

    returns = []


    # ----------------------------------------------
    # NUMBER OF ORDERS
    # ----------------------------------------------

    ORDER_COUNT = 10000


    # ----------------------------------------------
    # GENERATE ORDERS
    # ----------------------------------------------

    for order_id in range(
        1,
        ORDER_COUNT + 1
    ):

        # Generate order

        order = generate_order(
            customers,
            employees,
            regions
        )


        # Generate order items

        items = generate_order_items(
            order_id,
            products
        )


        # ------------------------------------------
        # GENERATE ORDER ITEM IDs
        # ------------------------------------------

        for i, item in enumerate(
            items,
            start=len(order_items) + 1
        ):

            item["order_item_id"] = i


        # ------------------------------------------
        # CALCULATE TOTAL
        # ------------------------------------------

        total_amount = calculate_order_total(
            items
        )


        # ------------------------------------------
        # ADD ORDER ID AND TOTAL
        # ------------------------------------------

        order["order_id"] = order_id

        order["total_amount"] = total_amount


        # ------------------------------------------
        # GENERATE PAYMENT
        # ------------------------------------------

        payment = generate_payment(
            order
        )


        # ------------------------------------------
        # GENERATE RETURNS
        # ------------------------------------------

        item_returns = generate_return(
            order,
            items
        )


        # ------------------------------------------
        # STORE DATA
        # ------------------------------------------

        orders.append(
            order
        )

        order_items.extend(
            items
        )

        payments.append(
            payment
        )

        returns.extend(
            item_returns
        )


    # ----------------------------------------------
    # CREATE DATAFRAMES
    # ----------------------------------------------

    orders_df = pd.DataFrame(
        orders
    )

    order_items_df = pd.DataFrame(
        order_items
    )

    payments_df = pd.DataFrame(
        payments
    )

    returns_df = pd.DataFrame(
        returns
    )

    save_to_csv(
    orders_df,
    order_items_df,
    payments_df,
    returns_df
)

    # ----------------------------------------------
    # DISPLAY RESULTS
    # ----------------------------------------------

    print("\n")
    print("=" * 60)
    print("ORDERS")
    print("=" * 60)

    print(
        orders_df
    )


    print("\n")
    print("=" * 60)
    print("ORDER ITEMS")
    print("=" * 60)

    print(
        order_items_df
    )


    print("\n")
    print("=" * 60)
    print("PAYMENTS")
    print("=" * 60)

    print(
        payments_df
    )


    print("\n")
    print("=" * 60)
    print("RETURNS")
    print("=" * 60)

    print(
        returns_df
    )


# --------------------------------------------------
# RUN PROGRAM
# --------------------------------------------------

if __name__ == "__main__":

    main()